### ISSUE TITLE
2024.1版本的homeassistant是不是已经不支持了

### ISSUE THREAD

**Issue by yunhai20082008** [5high/konke#10]
如题

**Comment by iamhaifeng** [comment]
HA版本：2024.2.2，添加本插件后报错，无法添加实体：

2024-03-24 17:40:14.593 ERROR (MainThread) [homeassistant.components.switch] Error while setting up konke platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/konke/switch.py", line 47, in async_setup_platform
    model = config[CONF_MODEL].lower()
            ~~~~~~^^^^^^^^^^^^
KeyError: 'model'

@5high

**Comment by iamhaifeng** [comment]
> HA版本：2024.2.2，添加本插件后报错，无法添加实体：
> 
> 2024-03-24 17:40:14.593 ERROR (MainThread) [homeassistant.components.switch] Error while setting up konke platform for switch Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/konke/switch.py", line 47, in async_setup_platform model = config[CONF_MODEL].lower() ~~~~~~^^^^^^^^^^^^ KeyError: 'model'
> 
> @5high

自己解决了，在configuration.yaml中，按以下格式进行配置：（添加model字段，建议修改README）

switch:
  - platform: konke
    name: switch_minik
    host: 192.168.1.xxx
    model: minik

**Comment by iamhaifeng** [comment]
#11

**Comment by iambbf** [comment]
HA版本：2024.7.1，添加本插件添加light后报错，无法添加灯光实体：
configuration.yaml中配置：
light:
  - platform: konke
    name: light
    host: 192.168.0.114
    model: kbulb
报错：
Platform error 'light' from integration 'konke' - cannot import name 'Light' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/init.py)

将light.py中的的 Light 改成 LightEntity 后，可接入智能灯泡进行控制

**Comment by ssyufeng** [comment]
求救大神minipro的插座遥控是不是失效了
remote:
  - platform: konke
    name: k_ir_remote
    model: minik
    host: 192.168.1.10
    hidden: false
    type: ir
配置警告
Platform error 'remote' from integration 'konke' - Exception importing custom_components.konke.remote
